---
title: "draft_analysis"
author: "Joe LaRocca"
date: "2026-01-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(readxl)
library(nflreadr)
```

## Upload and Clean Data

### PFR Draft Data

```{r}

drafts = load_draft_picks(seasons = 1994:2016)

# start in 1994 since that's when NFL draft first had the current seven-round format
# end in 2015 since we want players with >= 10 seasons of experience

draft_data_raw = drafts %>%
  select(season, round, pick, pfr_player_name, position, category, side, team, w_av, dr_av) %>%
  mutate(
    team = ifelse(team == "RAI", "LVR", team),
    team = ifelse(team == "OAK", "LVR", team),
    team = ifelse(team == "RAM", "LAR", team),
    team = ifelse(team == "STL", "LAR", team),
    team = ifelse(team == "SDG", "LAC", team),
    round = factor(round, levels = 1:7),
    draft_day = case_match(
      round,
      "1" ~ "Day 1",
      "2" ~ "Day 2",
      "3" ~ "Day 2",
      "4" ~ "Day 3",
      "5" ~ "Day 3",
      "6" ~ "Day 3",
      "7" ~ "Day 3"
    ),
    category = ifelse(category == "K" | category == "P" | category == "LS", "ST", category),
    category = factor(
      category,
      levels = c("QB", "RB", "WR", "TE", "OL", "DL", "LB", "DB", "ST")),
    side = case_match(
      side,
      "O" ~ "Offense",
      "D" ~ "Defense",
      "S" ~ "Special Teams"
    ),
    side = factor(side, levels = c("Offense", "Defense", "Special Teams")),
    w_av = ifelse(is.na(w_av), 0, w_av) # NA means no NFL snaps; therefore 0 AV,
    )

write_csv(draft_data, "Data/draft_data_consolidated_1994_2016.csv")

```

### Draft Value Charts

```{r}

draft_value_meers = read_excel("Data/nfl_draft_value_charts.xlsx", sheet = "DVC_New_Raw") %>%
  mutate(
    value = format(value, nsmall = 1),
    value = round(as.numeric(value), 1)
  ) %>%
  rename(meers_value = value)

draft_value_johnson = read_excel("Data/nfl_draft_value_charts.xlsx", sheet = "DVC_Original_Raw") %>%
  mutate(
    value = format(value, nsmall = 1),
    value = round(as.numeric(value), 1)
  ) %>%
  rename(johnson_value = value)

```

### Merged Data

```{r}

draft_data = draft_data_raw %>%
  left_join(draft_value_meers, by = "pick") %>%
  left_join(draft_value_johnson, by = "pick") %>%
  mutate(efficiency_overall = round(w_av / meers_value, 3),
         efficiency_team = round(dr_av / meers_value, 3),
        efficiency_overall_johnson = round(w_av / johnson_value, 3),
        efficiency_team_johnson = round(dr_av / johnson_value, 3),)

```

## Exploratory Data Analysis

### Total Weighted AV by Draft Season

```{r}

basic_av_plot = draft_data %>%
  group_by(season) %>%
  summarize(total_av = sum(w_av, na.rm = TRUE)) %>%
  mutate(season = factor(season, levels = rev(1994:2016))) %>%
  ggplot(aes(x = season, y = total_av, fill = season)) + 
  geom_bar(stat = "identity") +
  geom_col(color = "black", linewidth = 0.8) + 
  coord_flip() +
  scale_fill_viridis_d(option = "C", direction = -1) + 
  theme_classic() + 
  theme(legend.position = "none") + 
  labs(
    y = "Total Weighted AV",
    x = "Season"
  )

basic_av_plot

```

### Weighted AV Per Player, by Position Category

```{r}

draft_data %>%
  ggplot(aes(x = category, y = w_av, fill = side)) + 
  geom_boxplot() + 
  theme_classic() + 
  labs(
    y = "Weighted AV",
    x = "Position Group"
  ) + 
  theme(legend.title = element_blank())

```

### Weighted AV Per Player, by Position Category, by Day

```{r}

draft_data %>%
  ggplot(aes(x = category, y = w_av, fill = side)) + 
  geom_boxplot() + 
  theme_classic() + 
  labs(
    y = "Weighted AV",
    x = "Position Group"
  ) + 
  facet_wrap(~ draft_day) +
  theme(legend.title = element_blank())

```

### Scatterplots of Draft Value vs. Weighted AV

```{r}

scatter_johnson = draft_data %>%
  group_by(pick) %>%
  summarize(mean_av = mean(w_av, na.rm = TRUE)) %>%
  ungroup() %>%
  left_join(draft_value_meers, by = "pick") %>%
  left_join(draft_value_johnson, by = "pick") %>%
  ggplot(aes(x = johnson_value, y = mean_av)) + 
  geom_point() + 
  geom_smooth(method = "lm", col = "firebrick") + 
  geom_smooth() + 
  theme_classic() + 
  labs(
    title = "Johnson Method",
    x = "Pick Value (Johnson's Method)",
    y = "Mean Weighted AV"
  )

scatter_meers = draft_data %>%
  group_by(pick) %>%
  summarize(mean_av = mean(w_av, na.rm = TRUE)) %>%
  ungroup() %>%
  left_join(draft_value_meers, by = "pick") %>%
  left_join(draft_value_johnson, by = "pick") %>%
  ggplot(aes(x = meers_value, y = mean_av)) + 
  geom_point() + 
  geom_smooth(method = "lm", col = "firebrick") + 
  geom_smooth() + 
  theme_classic() + 
  labs(
    title = "Meers Method",
    x = "Pick Value",
    y = "Mean Weighted AV"
  )

plot_grid(plotlist = list(scatter_johnson, scatter_meers))

```

### Scatterplots of Draft Value vs. Weighted AV, By Position Group

```{r}

scatter_johnson_pos = draft_data %>%
  group_by(pick, category) %>%
  summarize(mean_av = mean(w_av, na.rm = TRUE)) %>%
  ungroup() %>%
  left_join(draft_value_meers, by = "pick") %>%
  left_join(draft_value_johnson, by = "pick") %>%
  ggplot(aes(x = johnson_value, y = mean_av)) +
  geom_point() + 
  geom_smooth(method = "lm", col = "firebrick") + 
  geom_smooth() + 
  theme_classic() + 
  facet_wrap(~ category) + 
  labs(
    title = "Johnson Method",
    x = "Pick Value",
    y = "Mean Weighted AV"
  )

scatter_johnson_pos

```


```{r}

scatter_meers_pos = draft_data %>%
  group_by(pick, category) %>%
  summarize(mean_av = mean(w_av, na.rm = TRUE)) %>%
  ungroup() %>%
  left_join(draft_value_meers, by = "pick") %>%
  left_join(draft_value_johnson, by = "pick") %>%
  ggplot(aes(x = meers_value, y = mean_av)) +
  geom_point() + 
  geom_smooth(method = "lm", col = "firebrick") + 
  geom_smooth() + 
  theme_classic() + 
  facet_wrap(~ category) + 
  labs(
    title = "Meers Method",
    x = "Pick Value",
    y = "Mean Weighted AV"
  )

```

## Building a Shiny Dashboard!

```{r}

draft_clean <- draft_data %>%
  transmute(
    season,
    team,
    round,
    pick_overall = pick,
    player = pfr_player_name,
    position,
    category,
    side,
    draft_day,

    # AV inputs
    w_av,
    dr_av,

    # draft value models
    meers_value,
    johnson_value,

    # precomputed draft value efficiencies
    efficiency_overall,  # w_av / meers_value
    efficiency_team,    # dr_av / meers_value
    efficiency_overall_johnson,
    efficiency_team_johnson
  ) %>%
  mutate(category = as.character(category))

write_rds(draft_clean, "Data/draft_shiny.rds")

```

```{r}

team_colors <- c(
  "ARI" = "#97233F",
  "ATL" = "#A71930",
  "BAL" = "#241773",
  "BUF" = "#00338D",
  "CAR" = "#0085CA",
  "CHI" = "#0B162A",
  "CIN" = "#FB4F14",
  "CLE" = "#311D00",
  "DAL" = "#003594",
  "DEN" = "#FB4F14",
  "DET" = "#0076B6",
  "GNB"  = "#203731",
  "HOU" = "#03202F",
  "IND" = "#002C5F",
  "JAX" = "#006778",
  "KAN"  = "#E31837",
  "LVR"  = "#000000",
  "LAC" = "#002A5E",
  "LAR" = "#0B0B0B",
  "MIA" = "#008E97",
  "MIN" = "#4F2683",
  "NWE"  = "#002244",
  "NOR"  = "#D3BC8D",
  "NYG" = "#0B2265",
  "NYJ" = "#125740",
  "PHI" = "#004C54",
  "PIT" = "#FFB612",
  "SEA" = "#002244",
  "SFO"  = "#AA0000",
  "TAM"  = "#D50A0A",
  "TEN" = "#4B92DB",
  "WAS" = "#5A1414"
)

```

